[tool.black]
line-length = 99
target-version = ["py311"]
skip-string-normalization = false

[tool.ruff]
line-length = 99
target-version = "py311"

[tool.ruff.lint]
select = [
  "E", "W",   # pycodestyle (PEP 8 checks)
  "F",        # pyflakes
  "I",        # import sorting (isort)
  "UP",       # pyupgrade
  "SIM",      # simplify
  "N",        # naming
  "B",        # bugbear
  "C4",       # comprehensions
  "TID",      # tidy imports
]
ignore = ["T201",  "D103", "D107", "B018", "N802", "PLR1702"]
# T201 - print() occurrences
# D103 - missing function docstrings --> for compactness
# D107 - missing class docstrings --> //
# B018 - unused loop vars --> for clarity, unless the loop is big
# N802 - camelCase not allowed --> allow for LC
# PLR1702 - combine if branches sharing the same body --> for clarity


[tool.ruff.lint.isort]
combine-as-imports = true
known-first-party = ["yourpkg"]

[tool.pydocstyle]
ignore = ["D100", "D101", "D102", "D103", "D107"]
